- name: converge
  hosts: all
  roles:
    - role: satellite
      satellite_proxy_dhcp_managed: false
      satellite_proxy_dns_managed: false
      satellite_admin_password: my_p4assW0rd
      satellite_compute_ec2: true
      satellite_compute_gce: true
      satellite_compute_libvirt: true
      satellite_compute_openstack: true
      satellite_compute_ovirt: true
      satellite_compute_rackspace: true
      satellite_compute_vmware: true
  post_tasks: []
